jenkins:
  systemMessage: "Jenkins Configured via JCasC"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin
    authorizationStrategy:
      loggedInUsersCanDoAnything:
        allowAnonymousRead: false

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: dockerhub-creds
              username: "${DOCKERHUB_USER}"
              password: "${DOCKERHUB_PASS}"
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: vm-ssh-creds
              username: ${VM_SSH_USER}
              privateKeySource:
                directEntry:
                  privateKey: "${SSH_PRIVATE_KEY}"

jobs:
  - script: >
      pipelineJob('spring-boot-ci') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/rmoloney96/spring-boot-api.git')
                }
                branches('*/main')
              }
            }
          }
        }
      }
